### ISSUE TITLE
Icons installing as 0x0 with Ubuntu .deb packages... 

### ISSUE THREAD

**Issue by burtonator** [electron-userland/electron-packager#857]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

Icon not being set on Ubunto 18.04 .. possibly due to incorrect size extraction.

I think the problem is that it's generating a 0x0 icon.  

I tried setting the file as icon-512.png or icon-512x512.png 

I confirmed that it is in fact a PNG by looking at the binary data.

The dpkg lists a file of:

/usr/share/icons/hicolor/0x0/apps/polar-bookshelf.png

AKA 0x0 in the path.  

yet this shows that it's 512x512

config looks like this:

```
productName: Polar Bookshelf
electronVersion: 2.0.2
appId: io.inputneuron/polar
compression: store
npmRebuild: false
directories:
  output: dist
  buildResources: .
  app: .

mac:
  category: Reference
  icon: ./icon-512x512.png
  target: dmg
  fileAssociations:
    - ext: "pdf"
      role: "Viewer"

linux:
  synopsis: Polar Bookshelf PDF reader
  description: Polar Bookshelf PDF reader
  category: Reference

  # https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon
  #
  # Linux: this option is not required, as the dock/window list icon is set via
  # the icon option in the BrowserWindow constructor. Please note that you need
  # to use a PNG, and not the OS X or Windows icon formats, in order for it to
  # show up in the dock/window list. Setting the icon in the file manager is not
  # currently supported.
  icon: ./icon-512x512.png
  fileAssociations:
    - ext: "pdf"

win:
  icon: icon-512x512.png
  fileAssociations:
    - ext: "pdf"


```

```shell
$ file /usr/share/icons/hicolor/0x0/apps/polar-bookshelf.png
/usr/share/icons/hicolor/0x0/apps/polar-bookshelf.png: PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
```

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
  • electron-builder version=20.15.1
  • loaded configuration file=/home/burton/projects/polar-bookshelf/electron-builder.yml
  • Specified application directory equals to project dir — superfluous or wrong configuration appDirectory=.
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=2.0.2 appOutDir=dist/linux-unpacked
(node:5584) ExperimentalWarning: The fs.promises API is experimental
  • building        target=tar.gz arch=x64 file=dist/polar-bookshelf-1.0.0-beta6.tar.gz
  • building        target=snap arch=x64 file=dist/polar-bookshelf_1.0.0-beta6_amd64.snap
  • path resolved             outputFormat=set path=/home/burton/projects/polar-bookshelf/icon-512.png
  • found existing            path=/home/burton/.cache/electron-builder/snap/snap-template-electron-2.3
  • copy files                from=/home/burton/projects/polar-bookshelf/icon-512.png isUseHardLinks=true to=/home/burton/projects/polar-bookshelf/dist/__snap-x64/meta/gui/icon.png
  • found existing            path=/home/burton/.cache/electron-builder/appimage/appimage-9.1.0
  • execute command           args=[/home/burton/.cache/electron-builder/appimage/appimage-9.1.0/linux-x64/mksquashfs /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/var /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/lib /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/bindtextdomain.so /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/bin /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/usr /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/flavor-select /home/burton/.cache/electron-builder/snap/snap-template-electron-2.3/etc /home/burton/projects/polar-bookshelf/dist/__snap-x64/meta /home/burton/projects/polar-bookshelf/dist/__snap-x64/command.sh /home/burton/projects/polar-bookshelf/dist/linux-unpacked/icudtl.dat /home/burton/projects/polar-bookshelf/dist/linux-unpacked/views_resources_200_percent.pak /home/burton/projects/polar-bookshelf/dist/linux-unpacked/LICENSE.electron.txt /home/burton/projects/polar-bookshelf/dist/linux-unpacked/blink_image_resources_200_percent.pak /home/burton/projects/polar-bookshelf/dist/linux-unpacked/natives_blob.bin /home/burton/projects/polar-bookshelf/dist/linux-unpacked/resources /home/burton/projects/polar-bookshelf/dist/linux-unpacked/content_resources_200_percent.pak /home/burton/projects/polar-bookshelf/dist/linux-unpacked/libnode.so /home/burton/projects/polar-bookshelf/dist/linux-unpacked/libffmpeg.so /home/burton/projects/polar-bookshelf/dist/linux-unpacked/LICENSES.chromium.html /home/burton/projects/polar-bookshelf/dist/linux-unpacked/snapshot_blob.bin /home/burton/projects/polar-bookshelf/dist/linux-unpacked/content_shell.pak /home/burton/projects/polar-bookshelf/dist/linux-unpacked/pdf_viewer_resources.pak /home/burton/projects/polar-bookshelf/dist/linux-unpacked/locales /home/burton/projects/polar-bookshelf/dist/linux-unpacked/polar-bookshelf /home/burton/projects/polar-bookshelf/dist/linux-unpacked/ui_resources_200_percent.pak /home/burton/projects/polar-bookshelf/dist/polar-bookshelf_1.0.0-beta6_amd64.snap -no-progress -quiet -noappend -comp xz -no-xattrs -no-fragments -all-root] path=/home/burton/.cache/electron-builder/appimage/appimage-9.1.0/linux-x64/mksquashfs
  • building        target=deb arch=x64 file=dist/polar-bookshelf_1.0.0-beta6_amd64.deb
  • found existing            path=/home/burton/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
electron-builder --config=electron-builder.yml --linux deb tar.gz snap --publish always

```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**
